version: '3.1'
services:
  postgres:
      image: postgres:10.3-alpine
      ports:
          - "5432:5432"
      expose:
          - "5432"
      environment:
          POSTGRES_DB: "goapisql_db"
          POSTGRES_PASSWORD: "goapisql_db_password"
      volumes:
          - /tmp:/tmp
          - /data/postgresql/goapisql_db:/var/lib/postgresql/data
      command: postgres -c log_destination=stderr -c logging_collector=on -c log_directory=/tmp -c log_statement=all -c log_duration=on
      container_name: postgres-goapisql

  postgres_test:
    image: postgres:10.3-alpine
    ports:
    - "5433:5432"
    expose:
    - "5433"
    environment:
      POSTGRES_DB: "goapisql_db_test"
      POSTGRES_PASSWORD: "goapisql_db_password_test"
    volumes:
    - /tmp:/tmp
    - /data/postgresql/goapisql_db_test:/var/lib/postgresql/data
    command: postgres -c log_destination=stderr -c logging_collector=on -c log_directory=/tmp -c log_statement=all -c log_duration=on
    container_name: postgres-goapisql-test

